openapi: 3.0.0
info:
  description: |
    ## Overview 

    This is the API description for Sniffie's Orders API.     
    - 100 requests per second
    - 200 orders per request
    
    When possible, send max item count instead of one item per request to avoid overflooding the API.

    You can get the token from our customer service, make sure it is in form of {accountId}&&{token}
  version: 1.0.0
  title: Sniffie Orders API
servers:
  - url: https://api.sniffie.io/v1/account-orders
  - url: https://api.sniffie-staging.io/v1/orders-products
tags:
  - name: orders
    description: Manage orders of an account
security:
  - ApiKeyAuth: []
paths:
  /{accountId}/orders:
    post:
      tags:
        - orders
      summary: Creates a new order history item
      description: Inserts a orderHistory row
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/OrderInputList'
                - $ref: '#/components/schemas/OrderInput'
      parameters:
        - name: accountId
          in: path
          description: AccountId of of the account in question
          required: true
          schema:
            type: integer
            format: int64
        
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResult'
        400:
          description: Check request, invalid payload
        429:
          description: Too many requests, slow down request rate and retry
        500:
          $ref: '#/components/responses/5XX'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
  responses:
    5XX:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
              
    OrderResult:
      type: object
      properties:
        requestId:
          type: string
          description: Api gateway request Id
        data:
          $ref: '#/components/schemas/OrderInput'
    OrderInputList:
      type: array
      items:
        $ref: '#/components/schemas/OrderInput'
      maxItems: 200
    OrderInput:
      type: object
      required:
        - shopName
        - orderNumber
        - createdAt
        - additionalDiscountAmountAppliedToOrder
        - totalDiscount
        - totalTaxAmount
        - totalPriceWithoutVat
        - orderItems
      properties:
        shopName:
          type: string
          description: Name of the shop
          example: 'www.acme-inc.com'
        orderNumber:
          type: string
          description: Order number of whole order 
          example: 'ORD9876-11'
        createdAt:
          type: string
          format: datetime
          description: Datetime of the creation date for the order in UTC
          example: '2021-03-20T09:12:28Z'
        additionalDiscountAmountAppliedToOrder:
          type: number
          format: decimal
          description: Amount of discount applied to the order in addition to line item discounts
          example: '0.00'
        totalDiscount:
          type: number
          format: decimal
          description: Total amount of discount applied to the order (all line item discounts + additionalDiscountAmountAppliedToOrder)
          example: '0.00'
        totalTaxAmount:
          type: number
          format: decimal
          description: Total tax amount of the order
          example: '23.99'
        totalPrice:
          type: number
          format: decimal
          description: Total price of the order (with VAT)
          example: '99.95'
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        bundlesInOrder:
          type: array
          items:
            $ref: '#/components/schemas/BundleItem'
        additionalProperties:
          type: object
          additionalProperties: true
          description: additional properties related to this order
          example: {"anyKeyYouWishGoesHere":"Any for this key goes here", "andAnotherKeyMightComeHereToo": "With its value here"}

    BundleItem:
      type: object
      required:
        - orderBundleLineItems
      properties:
        orderBundleLineItems:
          type: array
          description: List of order item ids on the order that create a single bundle
          example: ['ORD9876-11-1, ORD9876-11-2']
          items:
            type: string
    OrderItem:
      type: object
      required:
        - unitPrice
        - originalPrice
        - taxAmount
        - discountAmount
        - currency
        - quantity
        - sku
        - orderLineNumber
      properties:
        unitPrice:
          type: number
          format: decimal
          description: Price at which the product was sold (including vat, including discount)
          example: '99.95'
        originalPrice: 
          type: number
          format: decimal
          description: Original (RRP) price of the line item, including tax and excluding discount
          example: 99.95
        taxAmount:
          type: number
          format: decimal
          description: Amount of tax applied to the line item
          example: '23.99'
        discountAmount:
          type: number
          format: decimal
          description: Amount of discount applied to the line item
          example: '0.00'
        currency:
          type: string
          description: Three letter currency code as defined by ISO-4217
          format: iso-4217
          example: 'EUR'
        quantity:
          type: number
          description: How many items were sold of this particular sku
          example: '1'
        sku:
          type: string
          description: SKU of the product
          example: 'SKU-123456-Y4'
        orderLineNumber:
          type: string
          description: Order line number of the product line item 
          example: 'ORD9876-11-1'
        additionalProperties:
          type: object
          additionalProperties: true
          description: additional properties related to this line item          
        
       
