/* eslint-disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Send all orders to be updated in a jsonl file, where each json item is in its own row. Must include all orders for a given date for a product. Meaning, if you send one order for a product for 2025-01-17, you must send all orders for that product for that date.
 */
export interface OrderLineItem {
  /**
   * ID of the shop, channel, website, POS. Should match storeId in the Store object
   */
  soldFrom: string;
  /**
   * Order number of whole order
   */
  orderNumber: string;
  /**
   * Order line number of the product line item
   */
  orderLineNumber: string;
  /**
   * date-time of the creation date for the order in UTC
   */
  createdAt: string;
  /**
   * Price what the customer paid for the item (all discounts, taxes and other charges included)
   */
  price: number;
  /**
   * Three letter currency code as defined by ISO-4217
   */
  currency: string;
  /**
   * How many items were sold of this particular sku
   */
  quantity: number;
  /**
   * Unique global identifier for the product, needs to match the gid in the ProductVariant object. Grouping factor for sales analytics
   */
  productId: string;
  /**
   * Stock keeping unit of the product. This must match the sku in the ProductVariant object
   */
  sku?: string;
  /**
   * If the item is a part of a bundle, this field is used to group the bundles with matching id
   */
  bundleId?: string;
  /**
   * Amount of tax applied to the line item
   */
  taxAmount?: number;
  /**
   * Amount of discount applied to the line item
   */
  discountAmount?: number;
  /**
   * Original (RRP) price of the line item, including tax and excluding discount
   */
  originalPrice?: number;
  /**
   * additional properties related to this order
   */
  additionalProperties?: {};
}
/**
 * Send all variants to be updated in a jsonl file, where each json item is in its own row
 */
export interface ProductVariant {
  /**
   * Unique global identifier for the variant, to distinguish it from the other variants. Use sku if no other id is available
   */
  gid: string;
  /**
   * A grouping id with which the variant is tied to other variants. Used for grouping in analytics and pricing and user interface. Usually a parentProduct's id, if no other groups exist. If no grouping id exists, use gid
   */
  groupId: string;
  /**
   * Name of the group this variant belongs to. Will be used in the user interface to group the variants under the parent and display this value as the group name
   */
  groupName: string;
  /**
   * Name of the variant
   */
  variantName: string;
  /**
   * Price what the customer pays (with VAT)
   */
  price: number;
  /**
   * Compare at Price / Suggested retail price, expressed as a decimal number of major currency units. Required if onSale is true
   */
  compareAtPrice?: number;
  /**
   * Names of the categories the item is belongs to. Send them in order from highest to lowest. Used as a grouping factor amongst different items. If no category exists send ['All']
   */
  categories: string[];
  /**
   * Three letter currency code as defined by ISO-4217
   */
  currency: string;
  /**
   * SKU (stock keeping unit) of the product. This must match the sku in the orders
   */
  sku: string;
  /**
   * All costs related to the product, used to calculate margins. If cogsNotAvailable is true, send 0.01
   */
  cogs: number;
  /**
   * Provide cogs currency, if the cogs is in another currency other than the default. Three letter currency code as defined by ISO-4217
   */
  cogsCurrency?: string | null;
  /**
   * Amount of items available in stock. If stockCountNotAvailable is true, send 10000000
   */
  stockCount: number;
  /**
   * If the cogs are not available, send true. Otherwise it's considered false
   */
  cogsNotAvailable?: boolean | null;
  /**
   * Parent product id, if the variant is a child of a parent product.
   */
  parentProductId?: string | null;
  /**
   * Status of the product, is it active or disabled. Considered enabled by default
   */
  variantStatus?: "enabled" | "disabled" | null;
  /**
   * If the stock count is not available, send true. Otherwise it's considered false
   */
  stockCountNotAvailable?: boolean | null;
  /**
   * European Article Number. Unified code for products. Required for competitor matching
   */
  ean?: string;
  /**
   * Manufacturer
   */
  manufacturer?: string;
  /**
   * Brand of the product
   */
  productBrand?: string;
  /**
   * Url to the image of the product
   */
  imageUrl?: string | null;
  /**
   * Url to the product page
   */
  productUrl?: string;
  /**
   * What kind of a product is it
   */
  productType?: string;
  /**
   * if the product is on sale send true. Otherwise it's considered false
   */
  onSale?: boolean;
  /**
   * ISO Date for the price, if in the past
   */
  dateForPrice?: string;
  /**
   * Possible tags to help with grouping, searching and sorting
   */
  tags?: string[];
  /**
   * Target margin percentile for the product
   */
  marginTargetPercentile?: number;
  /**
   * Recommended retail price for the product
   */
  recommendedRetailPrice?: number;
  /**
   * Default vat rate in percentile. If multiple vat rates are used, use the supplemental data upload to send the vat rates for each variant per store
   */
  vatRate?: number;
  /**
   * Inventory policy for the product, can it continue selling even if the stock runs out. If no value is sent, the default is CONTINUE
   */
  inventoryPolicy?: "DENY" | "CONTINUE" | null;
  /**
   * Any and all other currencies and prices that the product may be sold at
   */
  otherPrices?: AlternativePrice[];
  /**
   * additional properties related to this product
   */
  additionalProperties?: {};
}
export interface AlternativePrice {
  /**
   * Price expressed as a decimal number of major currency units
   */
  price: number;
  /**
   * Three letter currency code as defined by ISO-4217
   */
  currency: string;
  /**
   * Compare at Price / Suggested retail price, expressed as a decimal number of major currency units
   */
  originalPrice?: number;
}
/**
 * Competitor variant is automatically matched to product variants by their sku.
 * That's why sku is mandatory, along with price and currency and the date when the price was collected.
 * Send all competitor variants to be updated in a jsonl file, where each json item is in its own row
 *
 */
export interface CompetitorProductVariant {
  /**
   * Unique global identifier for the variant, to distinguish it from the other variants. Use sku if no other id is available
   */
  gid: string;
  /**
   * Name of the competitor
   */
  competitorName: string;
  /**
   * Price what the customer pays (with VAT)
   */
  price: number;
  /**
   * ISO Date for the price
   */
  dateForPrice: string;
  /**
   * Three letter currency code as defined by ISO-4217
   */
  currency: string;
  /**
   * This must match the SKU of the product in the ProductVariant object to create a match
   */
  sku: string;
  /**
   * If the competitor product is supposed to be matched to a specific store, send the storeId here. Otherwise leave it empty. Must match the storeId in the Store object
   */
  storeId?: string | null;
  /**
   * Compare at Price / Suggested retail price, expressed as a decimal number of major currency units. Required if onSale is true
   */
  compareAtPrice?: number;
  /**
   * Url to the product page
   */
  productUrl?: string;
}
/**
 * A mapping object between store and products. Can be used to provide store specific overriding values e.g. price, group id (groupId) etc.
 */
export interface StoreProduct {
  /**
   * Identifier for the store, must match the store identifier in the Store object
   */
  storeId: string;
  /**
   * Unique global identifier for the product, needs to match the gid in the ProductVariant object
   */
  gid: string;
  /**
   * A grouping id with which the variant is tied to other variants. Used for grouping in analytics and pricing and user interface. If no grouping id exists, use gid
   */
  groupId?: string;
  /**
   * Name of the group this variant belongs to. Will be used in the user interface to group the variants under the parent and display this value as the group name
   */
  groupName?: string;
  /**
   * Name of the variant
   */
  variantName?: string;
  /**
   * Price what the customer pays (with VAT)
   */
  price?: number;
  /**
   * Compare at Price / Suggested retail price, expressed as a decimal number of major currency units. Required if onSale is true
   */
  compareAtPrice?: number;
  /**
   * ISO Date for the price
   */
  dateForPrice?: string;
  /**
   * Names of the categories the item is belongs to. Used as a grouping factor amongst different items. If no category exists send ['All']
   */
  categories?: string[];
  /**
   * Three letter currency code as defined by ISO-4217
   */
  currency?: string;
  /**
   * SKU (stock keeping unit) of the product. This must match the sku in the orders
   */
  sku?: string;
  /**
   * All costs related to the product, used to calculate margins. If cogsNotAvailable is true, send 0.01
   */
  cogs?: number;
  /**
   * Amount of items available in stock. If stockCountNotAvailable is true, send 10000000
   */
  stockCount?: number;
  /**
   * If the cogs are not available, send true. Otherwise it's considered false
   */
  cogsNotAvailable?: boolean;
  /**
   * Status of the product, is it active or disabled. Considered enabled by default
   */
  variantStatus?: "enabled" | "disabled" | null;
  /**
   * If the stock count is not available, send true. Otherwise it's considered false
   */
  stockCountNotAvailable?: boolean | null;
  /**
   * European Article Number. Unified code for products. Required for competitor matching
   */
  ean?: string;
  /**
   * Manufacturer
   */
  manufacturer?: string | null;
  /**
   * Brand of the product
   */
  productBrand?: string | null;
  /**
   * Url to the image of the product
   */
  imageUrl?: string | null;
  /**
   * Url to the product page
   */
  productUrl?: string | null;
  /**
   * What kind of a product is it
   */
  productType?: string;
  /**
   * If the product is on sale send true. Otherwise it's considered false
   */
  onSale?: boolean;
  /**
   * Possible tags to help with grouping, searching and sorting
   */
  tags?: string[];
  /**
   * Target margin percentile for the product
   */
  marginTargetPercentile?: number;
  /**
   * Recommended retail price for the product
   */
  recommendedRetailPrice?: number;
  /**
   * Default vat rate in percentile. If multiple vat rates are used, use the supplemental data upload to send the vat rates for each variant per store
   */
  vatRate?: number;
  /**
   * Any and all other currencies and prices that the product may be sold at
   */
  otherPrices?: AlternativePrice[];
  /**
   * additional properties related to this product
   */
  additionalProperties?: {};
}
/**
 * Send all store data to be updated in a jsonl file, where each json item is in its own row
 */
export interface Store {
  /**
   * id of the store, can be the same as name, but must be unique and match the storeId in the StoreProduct object, and the soldFrom in the OrderLineItem object
   */
  storeId: string;
  /**
   * Name of the store
   */
  storeName: string;
  /**
   * Is pricing enabled for the store
   */
  pricingEnabled: boolean;
  /**
   * Region where the store is located
   */
  region?: string;
  /**
   * Zone within the region where the store is located
   */
  zone?: string;
  /**
   * Additional attributes related to the store
   */
  additionalAttributes?: {};
}
/**
 * Send all supplemental data to be updated for products in a jsonl file, where each json item is in its own row
 */
export interface SupplementalData {
  /**
   * Unique global identifier that matches the product variant to which the data is to be added to
   */
  gid: string;
  /**
   * Any number of different attributes and values related to the supplemental data
   */
  additionalProperties?: {};
}
export interface BulkUploadResponse {
  requestId?: string;
  data?: {
    uploadUrl?: string;
    uploadFields?: {
      "Content-Type"?: string;
      "Content-Encoding"?: string;
      bucket?: string;
      "X-Amz-Algorithm"?: string;
      "X-Amz-Credential"?: string;
      "X-Amz-Date"?: string;
      "X-Amz-Security-Token"?: string;
      key?: string;
      Policy?: string;
      "X-Amz-Signature"?: string;
    };
  };
}
